# Generated by Django 5.0.4 on 2024-05-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quotes', models.CharField(max_length=250)),
                ('image', models.ImageField(default='image/hero-bg.jpg', upload_to='image')),
                ('description', models.TextField()),
                ('manager_img', models.ImageField(default='image/hero-bg.jpg', upload_to='image')),
                ('manager_name', models.CharField(max_length=100)),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('content_1', models.TextField()),
                ('content_2', models.TextField()),
                ('street', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('image', models.ImageField(default='image/hero-bg.jpg', upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('team_image', models.ImageField(default='image/hero-bg.jpg', upload_to='image')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
