# Generated by Django 5.0.4 on 2024-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(default='image/hero-bg.jpg', upload_to='image/inner'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_img',
            field=models.ImageField(default='image/hero-bg.jpg', upload_to='image/inner'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='image',
            field=models.ImageField(default='image/hero-bg.jpg', upload_to='image/home'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(null=True, upload_to='image/inner'),
        ),
    ]
