# Generated by Django 5.0.4 on 2024-05-07 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Basic Amenities', max_length=50)),
                ('person_min', models.IntegerField()),
                ('person_max', models.IntegerField()),
                ('wifi', models.CharField(max_length=50)),
                ('swimming', models.BooleanField(default=False)),
                ('meal', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('gym', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(default='image/room-1.png', upload_to='image')),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField()),
                ('promo', models.IntegerField()),
                ('description', models.TextField()),
                ('amenities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_room.amenities')),
            ],
        ),
    ]
