# Generated by Django 5.0.4 on 2024-05-09 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='name',
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(default='image/hero-bg.jpg', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='rating',
            field=models.IntegerField(blank=True, default=3, help_text='Enter a rating from 1 to 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
