# Generated by Django 5.0.4 on 2024-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
